# Generated by Django 4.2.7 on 2023-11-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_categorias_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contenido',
            field=models.TextField(default='sin contenido', max_length=10000),
        ),
        migrations.AddField(
            model_name='post',
            name='resumen',
            field=models.CharField(default='sin resumen', max_length=300),
        ),
    ]
