# Generated by Django 4.2.7 on 2023-11-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_post_now_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.ManyToManyField(default='Sin categoria', to='Accounts.categorias'),
        ),
    ]
